services:
  lgtm:
    image: grafana/otel-lgtm:latest
    pull_policy: missing
    container_name: lgtm
    ports:
    - 3000:3000
    - 4317:4317
    - 4318:4318
    - 9090:9090
    expose:
    - 3000
    volumes:
    - ./tempo-data:/data/tempo
    - ./grafana-data:/data/grafana
    - ./loki-data:/data/loki
    - ./loki-storage:/loki
    - ./p8s-storage:/data/prometheus
    networks:
    - network
  quarkus-rest-server:
    image: test/quarkus-rest-server:0.0.1-SNAPSHOT
    container_name: quarkus-rest-server
    ports:
    - 8083:8080
    - 9003:9000
    expose:
    - 8083
    - 9003
    environment:
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
    depends_on:
      lgtm:
        condition: service_started
    networks:
    - network
  quarkus-rest-client:
    image: test/quarkus-rest-client:0.0.1-SNAPSHOT
    container_name: quarkus-rest-client
    ports:
    - 5005:5005
    - 8080:8080
    - 9002:9000
    expose:
    - 5005
    - 8080
    - 9002
    environment:
      QUARKUS_OTEL_EXPORTER_OTLP_ENDPOINT: http://lgtm:4317
      QUARKUS_REST_CLIENT_API_SERVER_URL: http://quarkus-rest-server:8080
      ITERATIONS_NUMBER: 10000
    depends_on:
      lgtm:
        condition: service_started
      quarkus-rest-server:
        condition: service_started
    networks:
    - network
networks:
  network:
    driver: bridge
